spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/kanban_2
    username: postgres
    password: 123
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.PostgreSQLDialect
    open-in-view: false

server:
  port: 8080

springdoc:
  swagger-ui:
    path: /swagger-ui.html
    operationsSorter: alpha
    tagsSorter: alpha
  api-docs:
    path: /v3/api-docs

app:
  jwt:
    secret: changeitchangethisverysecretkey1234567890
    expiration-ms: 86400000
